export const stoneFields = [
  "stone_id", "material_type", "weight_ct", "dimensions_mm", "shape", "cut",
  "colour_description", "clarity_transparency", "treatment", "origin_opinion",
  "laboratory", "report_number", "report_date", "evidence_source",
];

const stoneLabels = {
  en: { stone_id: "Stone", gemstone_name: "Gemstone", weight_ct: "Weight", shape: "Shape", treatment: "Treatment", report_status: "Report" },
  nl: { stone_id: "Steen", gemstone_name: "Edelsteen", weight_ct: "Gewicht", shape: "Vorm", treatment: "Behandeling", report_status: "Rapport" },
};

const detailLabels = {
  en: {
    stone_id: "Stone ID", material_type: "Natural or synthetic", weight_ct: "Weight", dimensions_mm: "Dimensions", shape: "Shape", cut: "Cut", colour_description: "Colour", clarity_transparency: "Transparency and clarity", treatment: "Treatment", origin_opinion: "Geographic origin opinion", laboratory: "Laboratory", report_number: "Report number", report_date: "Report date", evidence_source: "Source of this information",
  },
  nl: {
    stone_id: "Steennummer", material_type: "Natuurlijk of synthetisch", weight_ct: "Gewicht", dimensions_mm: "Afmetingen", shape: "Vorm", cut: "Slijpvorm", colour_description: "Kleur", clarity_transparency: "Transparantie en zuiverheid", treatment: "Behandeling", origin_opinion: "Oordeel over geografische herkomst", laboratory: "Laboratorium", report_number: "Rapportnummer", report_date: "Rapportdatum", evidence_source: "Bron van deze informatie",
  },
};

export const content = {
  en: {
    shared: {
      announcement: "Rubiae is preparing for launch. Purchasing is not yet available.",
      enquiryNote: "Your message does not reserve the stone or create an order.",
      navigation: { stones: "Stones", stories: "Stories", howToChoose: "How to Choose", about: "About", forTrade: "For Trade", contact: "Contact" },
      ctas: { exploreStones: "Explore the stones", registerInterest: "Register interest", askStone: "Ask about this stone", readMoment: "Read her moment", discoverMoments: "Discover Rubiae Moments", howToChoose: "How to choose", describeStones: "How we describe stones", contact: "Contact Rubiae", sendMessage: "Send message" },
      footer: { closingLine: "Choose on your terms.", links: ["Stones", "Stories", "How to Choose", "About", "For Trade", "Privacy", "Cookies", "Contact", "Instagram"], previewNote: "Rubiae is preparing for launch. Purchasing is not yet available.", copyright: "© {{CURRENT_YEAR}} Rubiae" },
      imageAlt: "Ruby jewellery beside a worn notebook on a cool grey table.",
      seo: {
        home: { title: "Rubiae — Natural gemstones, honestly described", description: "Choose a natural gemstone slowly, with clear information and room for personal meaning. Rubiae is preparing for launch in the Netherlands." },
        stones: { title: "Stones — Rubiae", description: "Preview individual gemstones with the facts currently known. Purchasing is not yet available." },
        stories: { title: "Rubiae Moments — Stories on her terms", description: "Personal moments shared only with permission and in her own words." },
        howToChoose: { title: "How to choose a gemstone — Rubiae", description: "Look at colour and character, understand the facts, ask clearly, and choose on your terms." },
        about: { title: "About Rubiae", description: "A quieter, honest way to discover and choose natural gemstones in the Netherlands." },
        forTrade: { title: "Gemstones for professional buyers — Rubiae", description: "Rubiae is preparing selected coloured gemstone material for verified professional buyers." },
        contact: { title: "Contact Rubiae", description: "Ask about a gemstone, report, future collection, or professional requirement." },
        privacy: { title: "Privacy — Rubiae", description: "How Rubiae handles personal data submitted through the preview website." },
        cookies: { title: "Cookies — Rubiae", description: "How Rubiae uses necessary and optional cookies and how you can manage your choice." },
      },
    },
    pages: {
      home: { hero: { eyebrow: "Natural gemstones", heading: "Choose a stone for the life you are shaping.", body: "Natural gemstones, honestly described and chosen on your terms.", cta: "Explore the stones", factCue: "What is known, clearly stated.", storyEyebrow: "RUBIAE MOMENTS", storyHeading: "Her story, in her own words.", storyCta: "Read her moment" }, slowLook: { displayLine: "A stone, seen slowly.", heading: "Begin with the stone.", body: "Colour, natural character, and what is known — clearly described.", cta: "Explore the stones" }, chooseFreely: { displayLines: ["Look slowly.", "Ask clearly.", "Choose freely."], cta: "How to choose" }, moments: { heading: "A moment can begin with a stone.", body: "Rubiae Moments is a space for stories shared in her own words.", cta: "Discover Rubiae Moments" }, facts: { heading: "For those who need the facts.", ctaDescription: "How we describe stones", ctaTrade: "For Trade" }, closing: { heading: "Choose on your terms.", cta: "Explore the stones" } },
      stones: { eyebrow: "STONES", heading: "Stones, considered one at a time.", intro: "Each stone is shown with the facts currently known. Look slowly, compare what matters to you, and ask before deciding.", previewNote: "The collection is shown for preview. Prices and purchasing will be added only when Rubiae is ready to trade.", fieldLabels: stoneLabels.en, emptyState: "The first stones are being documented. Register for a launch notice or return soon.", status: "Preview — not yet available for purchase", cta: "Ask about this stone" },
      stoneDetail: { eyebrow: "STONE {{stone_id}}", heading: "{{gemstone_name}}", status: "Preview — not yet available for purchase", intro: "A closer look at this individual stone, including what is known, what remains unknown, and the evidence available.", fieldLabels: detailLabels.en, factsHeading: "What is known", factsBody: "We separate laboratory conclusions, supplier statements, and information that is still unknown. Ask us if you would like to understand the limits of any statement or report.", cta: "Ask about this stone", unknown: "Unknown" },
      stories: { eyebrow: "RUBIAE MOMENTS", heading: "Stories, shared on her terms.", intro: "A stone may mark a beginning, a change, a promise, or something that needs no public name. Each story belongs first to the person who lived it.", emptyState: "Rubiae Moments is being prepared. No personal story is published without clear permission.", detailLabel: "Shared in her own words." },
      howToChoose: { eyebrow: "HOW TO CHOOSE", heading: "Look slowly. Ask clearly. Choose freely.", intro: "A gemstone can be beautiful before it is perfect, rare, or expensive. Start with what you notice, then ask what can be known.", sections: [{ heading: "Begin with colour and character", body: "Notice the colour in different light, the shape, the cut, and the natural features that make the stone individual." }, { heading: "Read the description carefully", body: "Weight, dimensions, treatment, origin opinions, and reports answer different questions. Unknown information should remain visible as unknown." }, { heading: "Separate fact from interpretation", body: "A laboratory conclusion, a supplier statement, and a personal impression do not carry the same certainty. Rubiae labels the source of each claim." }, { heading: "Ask before deciding", body: "Ask about the report, treatment, visible features, photography, or anything that affects your choice. A careful question is part of choosing well." }, { heading: "Choose on your terms", body: "You do not need a dramatic reason. You may choose for colour, curiosity, a private milestone, or simply because the stone feels right to you." }], cta: "Explore the stones" },
      about: { eyebrow: "ABOUT RUBIAE", heading: "A quieter way to choose a gemstone.", paragraphs: ["Rubiae brings natural gemstones into view without turning them into promises about the person who chooses them.", "We believe in looking slowly, describing honestly, and leaving space for personal meaning. The stone is presented with its character and the evidence available; the choice remains yours.", "Rubiae is being built in the Netherlands. The public site is currently a preview, while the collection, reports, and future service are prepared with care."], cta: "Contact Rubiae" },
      forTrade: { eyebrow: "FOR TRADE", heading: "Clear stones. Clear information.", intro: "Rubiae is preparing a focused supply of coloured gemstones for jewellers, designers, collectors, and other professional buyers.", focusHeading: "Current areas of focus", focusItems: ["Selected cutting rough", "Commercial cutting rough parcels", "Ruby specimens with matrix", "Finished loose stones"], processHeading: "A professional enquiry starts with the facts.", processBody: "Tell us the material, format, quantity, quality range, and documentation you need. Wholesale inventory, pricing, and terms are shared only after professional-buyer verification.", cta: "Introduce your requirements" },
      contact: { heading: "Ask clearly.", intro: "Ask about a stone, a report, the future collection, or a professional requirement. Rubiae aims to reply personally within one working day.", fieldLabels: { name: "Name", email: "Email", stone_id: "Stone ID", preferred_language: "Preferred language", message: "Message (optional)" }, privacyNote: "We use these details to answer your enquiry. See our Privacy notice.", launchNotice: "Email me when Rubiae opens for purchasing. I understand that I must confirm this separately by email.", submit: "Send enquiry", errors: { name: "Enter your name.", email: "Enter a valid email address.", preferred_language: "Select your preferred language.", stone_id: "Enter the stone ID.", send: "We could not send your message. Your information has not been submitted. Try again or email {{CONTACT_EMAIL}}." } },
      confirmation: { heading: "Thank you. Your message has been received. This does not reserve the stone, create an order, require payment, or give priority. Rubiae aims to reply personally within one working day." },
      privacy: { title: "Privacy", intro: "This notice explains how {{LEGAL_NAME}}, trading as Rubiae, uses personal data on {{DOMAIN}}.", sections: { dataCollected: "We collect the information you choose to provide in contact and interest forms: name, email address, preferred language, stone ID, optional message, and any separate launch-notification consent.", purpose: "We use enquiry data to answer your request and maintain a record of the conversation. We use launch-notification data only after separate consent and email confirmation.", legalBasis: "We process enquiries to take steps at your request and, where applicable, for our legitimate interest in answering and documenting genuine enquiries. We send launch notifications only with consent.", sharing: "We share data only with service providers needed to operate the website, forms, email, and security. They may include Shopify and the providers listed in the current processor register. We do not sell personal data.", internationalProcessing: "If a provider processes data outside the European Economic Area, we use the safeguards described by that provider and required by applicable law.", retention: "Unconverted enquiries are kept for up to 12 months. Launch-notification data is removed when you unsubscribe or after 24 months without interaction, unless a shorter period is required.", rights: "You may ask for access, correction, deletion, restriction, portability, or object to certain processing. You may withdraw consent at any time without affecting earlier lawful processing.", contact: "Email {{PRIVACY_EMAIL}}. You may also complain to the Dutch Data Protection Authority.", version: "Last updated: {{PRIVACY_VERSION_DATE}}" } },
      cookies: { title: "Cookies", intro: "Rubiae uses necessary cookies to operate and secure the website. Optional analytics or marketing technologies remain off unless you actively accept them.", choice: "You may accept, reject, or choose optional categories. Refusing optional cookies does not block the public website or future checkout.", change: "You can change or withdraw your choice at any time through Cookie settings.", inventoryLabels: ["Name", "Provider", "Purpose", "Category", "Duration"], buttons: { accept: "Accept optional cookies", reject: "Reject optional cookies", choose: "Choose settings", save: "Save choices" } },
      notFound: { heading: "This page is not here.", body: "Return to the stones or continue exploring Rubiae.", cta: "Return home" },
      system: { loading: "Loading", noResults: "No stones match this view.", retry: "Try again", menuOpen: "Open menu", menuClose: "Close menu", changeLanguage: "Change language" },
    },
  },
  nl: {
    shared: {
      announcement: "Rubiae bereidt de lancering voor. Aankopen is nog niet mogelijk.",
      enquiryNote: "Je bericht reserveert de steen niet en vormt geen bestelling.",
      navigation: { stones: "Stenen", stories: "Verhalen", howToChoose: "Hoe kies je", about: "Over Rubiae", forTrade: "Voor professionals", contact: "Contact" },
      ctas: { exploreStones: "Bekijk de stenen", registerInterest: "Interesse registreren", askStone: "Vraag naar deze steen", readMoment: "Lees haar moment", discoverMoments: "Ontdek Rubiae Moments", howToChoose: "Hoe kies je", describeStones: "Hoe we stenen beschrijven", contact: "Neem contact op met Rubiae", sendMessage: "Verstuur bericht" },
      footer: { closingLine: "Kies op jouw voorwaarden.", links: ["Stenen", "Verhalen", "Hoe kies je", "Over Rubiae", "Voor professionals", "Privacy", "Cookies", "Contact", "Instagram"], previewNote: "Rubiae bereidt de lancering voor. Aankopen is nog niet mogelijk.", copyright: "© {{CURRENT_YEAR}} Rubiae" },
      imageAlt: "Robijnsieraad naast een gebruikt notitieboek op een koelgrijze tafel.",
      seo: {
        home: { title: "Rubiae — Natuurlijke edelstenen, eerlijk beschreven", description: "Kies rustig een natuurlijke edelsteen, met heldere informatie en ruimte voor persoonlijke betekenis. Rubiae bereidt de lancering in Nederland voor." },
        stones: { title: "Stenen — Rubiae", description: "Bekijk afzonderlijke edelstenen met de feiten die nu bekend zijn. Aankopen is nog niet mogelijk." },
        stories: { title: "Rubiae Moments — Verhalen op haar voorwaarden", description: "Persoonlijke momenten, alleen met toestemming en in haar eigen woorden gedeeld." },
        howToChoose: { title: "Hoe kies je een edelsteen — Rubiae", description: "Bekijk kleur en karakter, begrijp de feiten, vraag door en kies op jouw voorwaarden." },
        about: { title: "Over Rubiae", description: "Een rustigere, eerlijke manier om natuurlijke edelstenen in Nederland te ontdekken en te kiezen." },
        forTrade: { title: "Edelstenen voor professionele kopers — Rubiae", description: "Rubiae bereidt geselecteerd gekleurd edelsteenmateriaal voor geverifieerde professionele kopers voor." },
        contact: { title: "Contact met Rubiae", description: "Vraag naar een edelsteen, rapport, toekomstige collectie of professionele behoefte." },
        privacy: { title: "Privacy — Rubiae", description: "Hoe Rubiae omgaat met persoonsgegevens die via de voorvertoningswebsite worden verstrekt." },
        cookies: { title: "Cookies — Rubiae", description: "Hoe Rubiae noodzakelijke en optionele cookies gebruikt en hoe je jouw keuze beheert." },
      },
    },
    pages: {
      home: { hero: { eyebrow: "Natuurlijke edelstenen", heading: "Kies een steen voor het leven dat je vormgeeft.", body: "Natuurlijke edelstenen, eerlijk beschreven en gekozen op jouw voorwaarden.", cta: "Bekijk de stenen", factCue: "Wat bekend is, helder vermeld.", storyEyebrow: "RUBIAE MOMENTS", storyHeading: "Haar verhaal, in haar eigen woorden.", storyCta: "Lees haar moment" }, slowLook: { displayLine: "Een steen, rustig bekeken.", heading: "Begin bij de steen.", body: "Kleur, natuurlijk karakter en wat bekend is — helder beschreven.", cta: "Bekijk de stenen" }, chooseFreely: { displayLines: ["Kijk rustig.", "Vraag door.", "Kies vrij."], cta: "Hoe kies je" }, moments: { heading: "Een moment kan beginnen met een steen.", body: "Rubiae Moments biedt ruimte aan verhalen, verteld in haar eigen woorden.", cta: "Ontdek Rubiae Moments" }, facts: { heading: "Voor wie de feiten nodig heeft.", ctaDescription: "Hoe we stenen beschrijven", ctaTrade: "Voor professionals" }, closing: { heading: "Kies op jouw voorwaarden.", cta: "Bekijk de stenen" } },
      stones: { eyebrow: "STENEN", heading: "Stenen, één voor één bekeken.", intro: "Elke steen wordt getoond met de feiten die nu bekend zijn. Kijk rustig, vergelijk wat voor jou telt en stel vragen voordat je beslist.", previewNote: "De collectie is nu een voorvertoning. Prijzen en aankoopmogelijkheden volgen pas wanneer Rubiae klaar is om te verkopen.", fieldLabels: stoneLabels.nl, emptyState: "De eerste stenen worden gedocumenteerd. Meld je aan voor een lanceringsbericht of kom binnenkort terug.", status: "Voorvertoning — nog niet te koop", cta: "Vraag naar deze steen" },
      stoneDetail: { eyebrow: "STEEN {{stone_id}}", heading: "{{gemstone_name_nl}}", status: "Voorvertoning — nog niet te koop", intro: "Bekijk deze afzonderlijke steen van dichtbij, met wat bekend is, wat nog onbekend is en welk bewijs beschikbaar is.", fieldLabels: detailLabels.nl, factsHeading: "Wat bekend is", factsBody: "We maken onderscheid tussen laboratoriumconclusies, verklaringen van leveranciers en informatie die nog onbekend is. Vraag ons gerust naar de beperkingen van een verklaring of rapport.", cta: "Vraag naar deze steen", unknown: "Onbekend" },
      stories: { eyebrow: "RUBIAE MOMENTS", heading: "Verhalen, gedeeld op haar voorwaarden.", intro: "Een steen kan een begin, een verandering, een belofte of iets zonder openbare naam markeren. Elk verhaal behoort in de eerste plaats toe aan degene die het heeft geleefd.", emptyState: "Rubiae Moments wordt voorbereid. Geen persoonlijk verhaal wordt zonder duidelijke toestemming gepubliceerd.", detailLabel: "Verteld in haar eigen woorden." },
      howToChoose: { eyebrow: "HOE KIES JE", heading: "Kijk rustig. Vraag door. Kies vrij.", intro: "Een edelsteen kan mooi zijn voordat hij perfect, zeldzaam of kostbaar is. Begin met wat je opvalt en vraag daarna wat er bekend kan zijn.", sections: [{ heading: "Begin bij kleur en karakter", body: "Bekijk de kleur in verschillend licht, de vorm, het slijpsel en de natuurlijke kenmerken die de steen eigen maken." }, { heading: "Lees de beschrijving aandachtig", body: "Gewicht, afmetingen, behandeling, herkomstoordelen en rapporten beantwoorden verschillende vragen. Onbekende informatie moet zichtbaar onbekend blijven." }, { heading: "Scheid feiten van interpretatie", body: "Een laboratoriumconclusie, een verklaring van een leverancier en een persoonlijke indruk bieden niet dezelfde zekerheid. Rubiae vermeldt de bron van elke bewering." }, { heading: "Vraag voordat je beslist", body: "Vraag naar het rapport, de behandeling, zichtbare kenmerken, fotografie of alles wat jouw keuze beïnvloedt. Een zorgvuldige vraag hoort bij goed kiezen." }, { heading: "Kies op jouw voorwaarden", body: "Je hebt geen groot verhaal nodig. Je kunt kiezen om de kleur, uit nieuwsgierigheid, voor een persoonlijk moment of eenvoudigweg omdat de steen bij je past." }], cta: "Bekijk de stenen" },
      about: { eyebrow: "OVER RUBIAE", heading: "Een rustigere manier om een edelsteen te kiezen.", paragraphs: ["Rubiae brengt natuurlijke edelstenen in beeld zonder er beloften van te maken over de persoon die ze kiest.", "We geloven in rustig kijken, eerlijk beschrijven en ruimte laten voor persoonlijke betekenis. De steen wordt getoond met zijn karakter en het beschikbare bewijs; de keuze blijft van jou.", "Rubiae wordt opgebouwd in Nederland. De openbare website is nu een voorvertoning, terwijl de collectie, rapporten en toekomstige dienstverlening zorgvuldig worden voorbereid."], cta: "Neem contact op met Rubiae" },
      forTrade: { eyebrow: "VOOR PROFESSIONALS", heading: "Duidelijke stenen. Duidelijke informatie.", intro: "Rubiae bereidt een gerichte selectie gekleurde edelstenen voor juweliers, ontwerpers, verzamelaars en andere professionele kopers voor.", focusHeading: "Huidige aandachtspunten", focusItems: ["Geselecteerd slijpruw", "Commerciële partijen slijpruw", "Robijnspecimens met moedergesteente", "Geslepen losse stenen"], processHeading: "Een professionele aanvraag begint bij de feiten.", processBody: "Vertel welk materiaal, formaat, volume, kwaliteitsniveau en welke documentatie je nodig hebt. Groothandelsvoorraad, prijzen en voorwaarden worden pas gedeeld nadat de professionele koper is geverifieerd.", cta: "Beschrijf je aanvraag" },
      contact: { heading: "Vraag gerust door.", intro: "Vraag naar een steen, een rapport, de toekomstige collectie of een professionele behoefte. Rubiae streeft ernaar binnen één werkdag persoonlijk te antwoorden.", fieldLabels: { name: "Naam", email: "E-mail", stone_id: "Steennummer", preferred_language: "Voorkeurstaal", message: "Bericht (optioneel)" }, privacyNote: "We gebruiken deze gegevens om je vraag te beantwoorden. Lees onze privacyverklaring.", launchNotice: "E-mail mij wanneer aankopen bij Rubiae mogelijk worden. Ik begrijp dat ik dit apart per e-mail moet bevestigen.", submit: "Verstuur aanvraag", errors: { name: "Vul je naam in.", email: "Vul een geldig e-mailadres in.", preferred_language: "Kies je voorkeurstaal.", stone_id: "Vul het steennummer in.", send: "We konden je bericht niet versturen. Je gegevens zijn niet verzonden. Probeer het opnieuw of mail naar {{CONTACT_EMAIL}}." } },
      confirmation: { heading: "Dank je. Je bericht is ontvangen. Dit reserveert de steen niet, vormt geen bestelling, vereist geen betaling en geeft geen voorrang. Rubiae streeft ernaar binnen één werkdag persoonlijk te antwoorden." },
      privacy: { title: "Privacy", intro: "Deze verklaring legt uit hoe {{LEGAL_NAME}}, handelend onder de naam Rubiae, persoonsgegevens gebruikt op {{DOMAIN}}.", sections: { dataCollected: "We verzamelen de gegevens die je zelf invult in contact- en interesseformulieren: naam, e-mailadres, voorkeurstaal, steennummer, optioneel bericht en eventuele afzonderlijke toestemming voor een lanceringsbericht.", purpose: "We gebruiken aanvraaggegevens om je vraag te beantwoorden en de correspondentie vast te leggen. Gegevens voor lanceringsberichten gebruiken we alleen na afzonderlijke toestemming en bevestiging per e-mail.", legalBasis: "We verwerken aanvragen om op jouw verzoek stappen te zetten en, waar van toepassing, op basis van ons gerechtvaardigd belang om echte aanvragen te beantwoorden en vast te leggen. Lanceringsberichten sturen we alleen met toestemming.", sharing: "We delen gegevens alleen met dienstverleners die nodig zijn voor de website, formulieren, e-mail en beveiliging. Daaronder kunnen Shopify en de leveranciers uit het actuele verwerkingsregister vallen. We verkopen geen persoonsgegevens.", internationalProcessing: "Als een dienstverlener gegevens buiten de Europese Economische Ruimte verwerkt, gebruiken we de waarborgen die de leverancier beschrijft en die de toepasselijke wet vereist.", retention: "Aanvragen die niet tot een klantrelatie leiden bewaren we maximaal 12 maanden. Gegevens voor lanceringsberichten verwijderen we na afmelding of na 24 maanden zonder interactie, tenzij een kortere termijn vereist is.", rights: "Je kunt vragen om inzage, correctie, verwijdering, beperking of overdraagbaarheid, of bezwaar maken tegen bepaalde verwerkingen. Toestemming kun je altijd intrekken zonder dat dit eerdere rechtmatige verwerking aantast.", contact: "E-mail {{PRIVACY_EMAIL}}. Je kunt ook een klacht indienen bij de Autoriteit Persoonsgegevens.", version: "Laatst bijgewerkt: {{PRIVACY_VERSION_DATE}}" } },
      cookies: { title: "Cookies", intro: "Rubiae gebruikt noodzakelijke cookies om de website te laten werken en te beveiligen. Optionele analyse- of marketingtechnologie blijft uit totdat je deze actief accepteert.", choice: "Je kunt optionele categorieën accepteren, weigeren of zelf kiezen. Het weigeren van optionele cookies blokkeert de openbare website of toekomstige checkout niet.", change: "Je kunt je keuze altijd wijzigen of intrekken via Cookie-instellingen.", inventoryLabels: ["Naam", "Aanbieder", "Doel", "Categorie", "Duur"], buttons: { accept: "Optionele cookies accepteren", reject: "Optionele cookies weigeren", choose: "Voorkeuren kiezen", save: "Keuzes opslaan" } },
      notFound: { heading: "Deze pagina is er niet.", body: "Ga terug naar de stenen of ontdek Rubiae verder.", cta: "Terug naar home" },
      system: { loading: "Laden", noResults: "Geen stenen passen bij deze weergave.", retry: "Probeer opnieuw", menuOpen: "Menu openen", menuClose: "Menu sluiten", changeLanguage: "Taal wijzigen" },
    },
  },
};
